version: '3'
services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/pg_data

    container_name: anylistdb
    # volumes:
    #   - ./postgres:/var/lib/postgres/data
